### ISSUE TITLE
[SRE] S1: PO tab crashes on load — TypeError: s.toLowerCase is not a function (regression from c4d7d13)

### ISSUE THREAD

**Issue by jerky-sre** [xrgarcia/jerky_shipping#18]
## Problem

The Purchase Orders tab crashes immediately on load with a `TypeError: s.toLowerCase is not a function` in a `useMemo`. The page is blank. Confirmed in production with browser DevTools.

This is a **regression introduced by commit `c4d7d13`** ("Improve date handling and user preferences for sales forecasting", 2026-03-06).

**Console output (production):**
```
Failed to load resource: /api/user-preferences/purchase-orders/velocity-end  (404)
Failed to load resource: /api/user-preferences/purchase-orders/velocity-start  (404)
TypeError: s.toLowerCase is not a function
    at index-Bv9bcCC1.js:911:8726
    at Object.e5 [as useMemo] (index-Bv9bcCC1.js:38:21401)
    at En.useMemo (index-Bv9bcCC1.js:9:6223)
    at UBe (index-Bv9bcCC1.js:911:8686)
```

## Root Cause

Commit `c4d7d13` migrated `velocityStart`/`velocityEnd` from `useState<Date>` to `useUserPreference<string>` + `parseLocalDate()`. 

When a user has **never set** their velocity window preferences (404s on both GET requests), the `useUserPreference` hook correctly falls back to default string values. However, the re-renders triggered by the 404 error state, combined with the existing `searchTerm` user preference (`"-13"` in the affected user's case), cause the `filtered` useMemo to execute its `toLowerCase` calls on a value that is **not a string** at some point in the render cycle.

**The `filtered` useMemo (line 2333) lacks type guards:**
```typescript
if (searchTerm) {
  const lower = searchTerm.toLowerCase();     // crashes if searchTerm is not a string
  rows = rows.filter((r: any) =>
    r.sku?.toLowerCase().includes(lower) ||   // crashes if r.sku is non-null non-string
    r.product_title?.toLowerCase().includes(lower) ||
    r.description?.toLowerCase().includes(lower)
  );
}
```

Note: `?.` only short-circuits on `null`/`undefined` — if a value is a truthy non-string (e.g., a number), `?.` does NOT prevent the crash.

**Similarly, `normalizeOpt` (line 292) has no type safety for label/value:**
```typescript
function normalizeOpt(opt: MultiSelectOption) {
  return typeof opt === "string" ? { label: opt, value: opt } : opt;
  // If opt is { label: null, value: "SKU" }, returns it unchanged
  // Then o.label.toLowerCase() crashes
}
```

### 1. Add type guards in `filtered` useMemo (`client/src/pages/forecasting.tsx` ~line 2333)

```typescript
if (searchTerm && typeof searchTerm === 'string') {
  const lower = searchTerm.toLowerCase();
  rows = rows.filter((r: any) =>
    (typeof r.sku === 'string' && r.sku.toLowerCase().includes(lower)) ||
    (typeof r.product_title === 'string' && r.product_title.toLowerCase().includes(lower)) ||
    (typeof r.description === 'string' && r.description.toLowerCase().includes(lower))
  );
}
```

### 2. Harden `normalizeOpt` to always return strings (`client/src/pages/forecasting.tsx` ~line 292)

```typescript
function normalizeOpt(opt: MultiSelectOption): { label: string; value: string; sublabel?: string } {
  if (typeof opt === "string") return { label: opt, value: opt };
  return {
    label: opt.label != null ? String(opt.label) : "",
    value: opt.value != null ? String(opt.value) : "",
    sublabel: opt.sublabel,
  };
}
```

### 3. Guard `parseLocalDate` against non-string input (`client/src/pages/forecasting.tsx` ~line 2056)

```typescript
function parseLocalDate(dateStr: string | null | undefined): Date {
  if (!dateStr || typeof dateStr !== 'string') {
    const d = new Date();
    d.setHours(0, 0, 0, 0);
    return d;
  }
  return new Date(dateStr + 'T00:00:00');
}
```

## Additional Context

**Affected user:** marc@jerky.com has `searchTerm: "-13"` saved in user preferences. This makes the search filter active on every mount, triggering the `toLowerCase` path immediately when snapshot data loads.

**Workaround for Marc right now:** His search term is the issue even before this crash. Once the crash is fixed, he should see "Clear Filters" in the PO toolbar — clicking it will clear his `"-13"` search term and all other PO filters from his preferences.

**Why it's S1:** Same as the previous GROUP BY bug — PO tab is completely inaccessible in production.

## Verification

1. Log in as a user with no saved `velocity-start`/`velocity-end` preferences
2. Open the Purchase Orders tab → should load without crash
3. Set a search term with a value like "-13", navigate away, return → should still load
4. Confirm "Clear Filters" button appears and clears the search term
